import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  background: {
    flex: 1,                // 👈 ocupa todo el espacio disponible
    justifyContent: 'center',
  },
  overlay: {
    flex: 1,
    padding: 24,
    justifyContent: 'center',
    gap: 16,
    backgroundColor: 'rgba(0,0,0,0.5)', // oscurece el fondo
  },
  logo: {
    width: 250,
    height: 120,
    alignSelf: 'center',
    marginBottom: 10,
  },
  title: {
    fontSize: 30,
    color: '#fff',
    marginBottom: 32,
    fontWeight: 'bold',
    textAlign: 'center',
    letterSpacing: 1.2,
  },
  input: {
    width: '100%',
    backgroundColor: '#3d3180ff',
    borderRadius: 10,
    paddingVertical: 14,
    paddingHorizontal: 16,
    fontSize: 16,
    color: '#fff',
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#2D333B',
  },
  button: {
    backgroundColor: '#DB4437',
    paddingVertical: 14,
    borderRadius: 10,
    marginBottom: 16,
    width: '100%',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 3,
  },
  fbButton: {
    backgroundColor: '#4267B2',
    paddingVertical: 14,
    borderRadius: 10,
    marginBottom: 16,
    width: '100%',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 3,
  },
  anonButton: {
    backgroundColor: '#6C757D',
    paddingVertical: 14,
    borderRadius: 10,
    marginTop: 8,
    width: '100%',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowOffset: { width: 0, height: 1 },
    shadowRadius: 3,
    elevation: 2,
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    letterSpacing: 0.5,
  },
});